### ISSUE TITLE
"Mark as Reviewed" button doesn't work

### ISSUE THREAD

**Issue by apratim1** [tcpd/surf#38] opened 2017-09-20 10:12 UTC
The Mark as Reviewed button doesn't work. If user selects mark as review button and then merges another data row then the highlighted data row turns back to its original color.

**Comment by Sudesh-Prakash-Singh** [comment] 2017-09-20 10:57
Duplicate of #32 . Closing.

**Closed as completed by Sudesh-Prakash-Singh** 2017-09-20 10:57 UTC
